name: Deploy to Donweb

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout del código del repositorio
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Configurar Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18 # Usa la versión compatible con tu proyecto Angular
        cache: 'npm'

    # 3. Instalar dependencias
    - name: Install dependencies
      run: npm install

    # 4. Construir la aplicación Angular en modo producción
    - name: Build Angular app
      run: npm run build --prod

    # 5. Subir archivos al servidor Donweb mediante FTP
    - name: Deploy to Donweb
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ftp://c2720874.ferozo.com # Cambia esto por el FTP de tu hosting
        username: ${{ secrets.DON_WEB_FTB_CLIENT }} # Define el usuario FTP en los secretos de GitHub
        password: ${{ secrets.DON_WEB_FTB_KEY }} # Define la contraseña FTP en los secretos de GitHub
        local-dir: dist/iphone-dinasty-final-page/browser/ # Ruta donde se encuentra la app construida
        server-dir: /public_html/ # Ruta del servidor en Donweb donde deseas subir los archivos

    # 6. Opcional: Limpiar archivos viejos del servidor (si aplica)
    - name: Clean up old files
      run: echo "Cleaning old files is managed by the FTP action"
